main: combat.c combat.h enemy.c enemy.h main.c menu.c menu.h player.c player.h screen.c screen.h utils.c utils.h
	clang -lmenu -lpanel -lncurses -Wall -o main combat.c enemy.c main.c menu.c player.c screen.c utils.c
